/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2014-2019 Bruno Augusto Nassif Travencolo.
 * All Rights Reserved.
 *
 * This file is part of DyNetVis Project (DyNetVis).
 *
 * How to cite this software:
 *  
@inproceedings{Linhares:2017:DSV:3019612.3019686,
 author = {Linhares, Claudio D. G. and Traven\c{c}olo, Bruno A. N. and Paiva, Jose Gustavo S. and Rocha, Luis E. C.},
 title = {DyNetVis: A System for Visualization of Dynamic Networks},
 booktitle = {Proceedings of the Symposium on Applied Computing},
 series = {SAC '17},
 year = {2017},
 isbn = {978-1-4503-4486-9},
 location = {Marrakech, Morocco},
 pages = {187--194},
 numpages = {8},
 url = {http://doi.acm.org/10.1145/3019612.3019686},
 doi = {10.1145/3019612.3019686},
 acmid = {3019686},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {complex networks, dynamic graph visualization, dynamic networks, recurrent neighbors, temporal activity map},
} 
 *  
 * DyNetVis is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * DyNetVis is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Lab of Complex Network Visualization at 
 * Federal University of Uberlândia, Brazil - (https://sites.google.com/view/dynetvis/team?authuser=0). 
 * The initial developer of the original code is Claudio D. G. Linhares <claudiodgl@gmail.com>.
 *
 * Contributor(s): Jean R. Ponciano -- jeanrobertop@gmail.com, Luis E. C. Rocha -- luis.rocha@ugent.be, 
 * José Gustavo S. Paiva -- gustavo@ufu.br, Bruno A. N. Travençolo -- travencolo@gmail.com
 *
 * You should have received a copy of the GNU General Public License along 
 * with DyNetVis. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package forms;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JDialog;

/**
 *
 * @author  Claudio Linhares
 */
public class NetworkProperties extends JDialog {

    public NetworkProperties(MainForm f) {
        initComponents();
        setAlwaysOnTop(true);
        frame = f;
        
        NumberFormat anotherFormat = NumberFormat.getNumberInstance(Locale.US);

        DecimalFormat anotherDFormat = (DecimalFormat) anotherFormat;
        anotherDFormat.setGroupingUsed(true);
        anotherDFormat.setGroupingSize(3);
  
        numberNodes.setText(anotherFormat.format(Long.parseLong(frame.numberNodes)));
        numberEdges.setText(anotherFormat.format(Long.parseLong(frame.numberEdges)));
        nameNetwork.setText(frame.nameFile);
        numberTimestamps.setText(anotherFormat.format(Long.parseLong(frame.numberTimestamps)));
        numberNetworkResolution.setText(frame.numberNetworkResolution);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JPanel();
        numberObjectsLabel2 = new javax.swing.JLabel();
        nameNetwork = new javax.swing.JTextField();
        numberObjectsLabel4 = new javax.swing.JLabel();
        numberNetworkResolution = new javax.swing.JTextField();
        numberObjectsLabel = new javax.swing.JLabel();
        numberNodes = new javax.swing.JTextField();
        numberObjectsLabel1 = new javax.swing.JLabel();
        numberEdges = new javax.swing.JTextField();
        numberObjectsLabel3 = new javax.swing.JLabel();
        numberTimestamps = new javax.swing.JTextField();
        dataPanel1 = new javax.swing.JPanel();
        numberObjectsLabel7 = new javax.swing.JLabel();
        overlappingEdges = new javax.swing.JTextField();
        numberObjectsLabel8 = new javax.swing.JLabel();
        avgEdgeSize = new javax.swing.JTextField();
        numberObjectsLabel10 = new javax.swing.JLabel();
        stdEdgeSize = new javax.swing.JTextField();
        numberObjectsLabel9 = new javax.swing.JLabel();
        intersections = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        generateMeasuresButton = new javax.swing.JButton();

        setTitle("Network Properties");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General Properties"));
        dataPanel.setMaximumSize(null);
        dataPanel.setLayout(new java.awt.GridLayout(5, 0, 5, 2));

        numberObjectsLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel2.setText("Name Network");
        dataPanel.add(numberObjectsLabel2);

        nameNetwork.setEditable(false);
        nameNetwork.setBackground(new java.awt.Color(255, 255, 255));
        nameNetwork.setColumns(7);
        nameNetwork.setForeground(new java.awt.Color(0, 0, 255));
        nameNetwork.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameNetwork.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameNetwork.setMinimumSize(new java.awt.Dimension(26, 20));
        nameNetwork.setRequestFocusEnabled(false);
        nameNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNetworkActionPerformed(evt);
            }
        });
        dataPanel.add(nameNetwork);

        numberObjectsLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel4.setText("Network Resolution");
        dataPanel.add(numberObjectsLabel4);

        numberNetworkResolution.setEditable(false);
        numberNetworkResolution.setBackground(new java.awt.Color(255, 255, 255));
        numberNetworkResolution.setColumns(7);
        numberNetworkResolution.setForeground(new java.awt.Color(0, 0, 255));
        numberNetworkResolution.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberNetworkResolution.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberNetworkResolution.setMinimumSize(new java.awt.Dimension(26, 20));
        numberNetworkResolution.setRequestFocusEnabled(false);
        numberNetworkResolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNetworkResolutionActionPerformed(evt);
            }
        });
        dataPanel.add(numberNetworkResolution);

        numberObjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel.setText("#Nodes");
        dataPanel.add(numberObjectsLabel);

        numberNodes.setEditable(false);
        numberNodes.setBackground(new java.awt.Color(255, 255, 255));
        numberNodes.setColumns(7);
        numberNodes.setForeground(new java.awt.Color(0, 0, 255));
        numberNodes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberNodes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberNodes.setMinimumSize(new java.awt.Dimension(26, 20));
        numberNodes.setRequestFocusEnabled(false);
        numberNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNodesActionPerformed(evt);
            }
        });
        dataPanel.add(numberNodes);

        numberObjectsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel1.setText("#Edges");
        dataPanel.add(numberObjectsLabel1);

        numberEdges.setEditable(false);
        numberEdges.setBackground(new java.awt.Color(255, 255, 255));
        numberEdges.setColumns(7);
        numberEdges.setForeground(new java.awt.Color(0, 0, 255));
        numberEdges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberEdges.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberEdges.setMinimumSize(new java.awt.Dimension(26, 20));
        numberEdges.setRequestFocusEnabled(false);
        numberEdges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEdgesActionPerformed(evt);
            }
        });
        dataPanel.add(numberEdges);

        numberObjectsLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel3.setText("#Timestamps");
        dataPanel.add(numberObjectsLabel3);

        numberTimestamps.setEditable(false);
        numberTimestamps.setBackground(new java.awt.Color(255, 255, 255));
        numberTimestamps.setColumns(7);
        numberTimestamps.setForeground(new java.awt.Color(0, 0, 255));
        numberTimestamps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberTimestamps.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberTimestamps.setMinimumSize(new java.awt.Dimension(26, 20));
        numberTimestamps.setRequestFocusEnabled(false);
        numberTimestamps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTimestampsActionPerformed(evt);
            }
        });
        dataPanel.add(numberTimestamps);

        getContentPane().add(dataPanel);

        dataPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Temporal Properties"));
        dataPanel1.setMaximumSize(null);
        dataPanel1.setLayout(new java.awt.GridLayout(5, 0, 5, 2));

        numberObjectsLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel7.setText("#Overlapping Edges");
        dataPanel1.add(numberObjectsLabel7);

        overlappingEdges.setEditable(false);
        overlappingEdges.setBackground(new java.awt.Color(255, 255, 255));
        overlappingEdges.setColumns(7);
        overlappingEdges.setForeground(new java.awt.Color(0, 0, 255));
        overlappingEdges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        overlappingEdges.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        overlappingEdges.setMinimumSize(new java.awt.Dimension(26, 20));
        overlappingEdges.setRequestFocusEnabled(false);
        overlappingEdges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overlappingEdgesActionPerformed(evt);
            }
        });
        dataPanel1.add(overlappingEdges);

        numberObjectsLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel8.setText("Avg Edge Size");
        dataPanel1.add(numberObjectsLabel8);

        avgEdgeSize.setEditable(false);
        avgEdgeSize.setBackground(new java.awt.Color(255, 255, 255));
        avgEdgeSize.setColumns(7);
        avgEdgeSize.setForeground(new java.awt.Color(0, 0, 255));
        avgEdgeSize.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        avgEdgeSize.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        avgEdgeSize.setMinimumSize(new java.awt.Dimension(26, 20));
        avgEdgeSize.setRequestFocusEnabled(false);
        avgEdgeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgEdgeSizeActionPerformed(evt);
            }
        });
        dataPanel1.add(avgEdgeSize);

        numberObjectsLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel10.setText("Std Deviation Edge Size");
        dataPanel1.add(numberObjectsLabel10);

        stdEdgeSize.setEditable(false);
        stdEdgeSize.setBackground(new java.awt.Color(255, 255, 255));
        stdEdgeSize.setColumns(7);
        stdEdgeSize.setForeground(new java.awt.Color(0, 0, 255));
        stdEdgeSize.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stdEdgeSize.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stdEdgeSize.setMinimumSize(new java.awt.Dimension(26, 20));
        stdEdgeSize.setRequestFocusEnabled(false);
        stdEdgeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdEdgeSizeActionPerformed(evt);
            }
        });
        dataPanel1.add(stdEdgeSize);

        numberObjectsLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberObjectsLabel9.setText("#Intersections");
        dataPanel1.add(numberObjectsLabel9);

        intersections.setEditable(false);
        intersections.setBackground(new java.awt.Color(255, 255, 255));
        intersections.setColumns(7);
        intersections.setForeground(new java.awt.Color(0, 0, 255));
        intersections.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        intersections.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        intersections.setMinimumSize(new java.awt.Dimension(26, 20));
        intersections.setRequestFocusEnabled(false);
        intersections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectionsActionPerformed(evt);
            }
        });
        dataPanel1.add(intersections);

        jLabel1.setText(" ");
        dataPanel1.add(jLabel1);

        generateMeasuresButton.setText("Generate Measures");
        generateMeasuresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateMeasuresButtonActionPerformed(evt);
            }
        });
        dataPanel1.add(generateMeasuresButton);

        getContentPane().add(dataPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void numberNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNodesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberNodesActionPerformed

    private void numberEdgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEdgesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberEdgesActionPerformed

    private void nameNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameNetworkActionPerformed

    private void numberTimestampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTimestampsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTimestampsActionPerformed

    private void numberNetworkResolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNetworkResolutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberNetworkResolutionActionPerformed

    private void overlappingEdgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overlappingEdgesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overlappingEdgesActionPerformed

    private void avgEdgeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgEdgeSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgEdgeSizeActionPerformed

    private void intersectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intersectionsActionPerformed

    private void generateMeasuresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateMeasuresButtonActionPerformed
        frame.getNetInline().verifyAvgEdgesSize();
        setEdgeTemporalStatistic();
    }//GEN-LAST:event_generateMeasuresButtonActionPerformed

    private void stdEdgeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdEdgeSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdEdgeSizeActionPerformed

    public void setEdgeTemporalStatistic() {
        
        NumberFormat anotherFormat = NumberFormat.getNumberInstance(Locale.US);

        DecimalFormat anotherDFormat = (DecimalFormat) anotherFormat;
        anotherDFormat.setGroupingUsed(true);
        anotherDFormat.setGroupingSize(3);
  
        overlappingEdges.setText(anotherFormat.format(frame.getNetInline().uniqueEdgesCrossing));
        avgEdgeSize.setText(frame.getNetInline().mediumEdgeSize+"");
        stdEdgeSize.setText(frame.getNetInline().stdEdgeSize+"");
        intersections.setText(anotherFormat.format(frame.getNetInline().countEdgesCrossing));
    }
    
     public void resetEdgeTemporalStatistic() {
        overlappingEdges.setText("");
        avgEdgeSize.setText("");
        stdEdgeSize.setText("");
        intersections.setText("");
    }
    
    public void display() {
        this.pack();
        this.setLocation(frame.getWidth()/2 + this.getWidth()/2, frame.getHeight()/2 - this.getHeight()/2);
        this.setVisible(true);
    }
    
    private MainForm frame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField avgEdgeSize;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel dataPanel1;
    private javax.swing.JButton generateMeasuresButton;
    protected javax.swing.JTextField intersections;
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JTextField nameNetwork;
    protected javax.swing.JTextField numberEdges;
    protected javax.swing.JTextField numberNetworkResolution;
    protected javax.swing.JTextField numberNodes;
    private javax.swing.JLabel numberObjectsLabel;
    private javax.swing.JLabel numberObjectsLabel1;
    private javax.swing.JLabel numberObjectsLabel10;
    private javax.swing.JLabel numberObjectsLabel2;
    private javax.swing.JLabel numberObjectsLabel3;
    private javax.swing.JLabel numberObjectsLabel4;
    private javax.swing.JLabel numberObjectsLabel7;
    private javax.swing.JLabel numberObjectsLabel8;
    private javax.swing.JLabel numberObjectsLabel9;
    protected javax.swing.JTextField numberTimestamps;
    protected javax.swing.JTextField overlappingEdges;
    protected javax.swing.JTextField stdEdgeSize;
    // End of variables declaration//GEN-END:variables

}