/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2014-2019 Bruno Augusto Nassif Travencolo.
 * All Rights Reserved.
 *
 * This file is part of DyNetVis Project (DyNetVis).
 *
 * How to cite this software:
 *  
@inproceedings{Linhares:2017:DSV:3019612.3019686,
 author = {Linhares, Claudio D. G. and Traven\c{c}olo, Bruno A. N. and Paiva, Jose Gustavo S. and Rocha, Luis E. C.},
 title = {DyNetVis: A System for Visualization of Dynamic Networks},
 booktitle = {Proceedings of the Symposium on Applied Computing},
 series = {SAC '17},
 year = {2017},
 isbn = {978-1-4503-4486-9},
 location = {Marrakech, Morocco},
 pages = {187--194},
 numpages = {8},
 url = {http://doi.acm.org/10.1145/3019612.3019686},
 doi = {10.1145/3019612.3019686},
 acmid = {3019686},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {complex networks, dynamic graph visualization, dynamic networks, recurrent neighbors, temporal activity map},
} 
 *  
 * DyNetVis is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * DyNetVis is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Lab of Complex Network Visualization at 
 * Federal University of Uberlândia, Brazil - (https://sites.google.com/view/dynetvis/team?authuser=0). 
 * The initial developer of the original code is Claudio D. G. Linhares <claudiodgl@gmail.com>.
 *
 * Contributor(s): Jean R. Ponciano -- jeanrobertop@gmail.com, Luis E. C. Rocha -- luis.rocha@ugent.be, 
 * José Gustavo S. Paiva -- gustavo@ufu.br, Bruno A. N. Travençolo -- travencolo@gmail.com
 *
 * You should have received a copy of the GNU General Public License along 
 * with DyNetVis. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package forms;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author  Claudio Linhares
 */
public class RandomWalker extends JDialog {

    public RandomWalker(MainForm f) {
        initComponents();
        setAlwaysOnTop(true);
        frame = f;
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        randomWalkerPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        runRandomWalker = new javax.swing.JButton();

        setTitle("Random Walker");
        setLocationByPlatform(true);
        setMaximumSize(null);
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        randomWalkerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        randomWalkerPanel.setMaximumSize(null);
        randomWalkerPanel.setName(""); // NOI18N
        randomWalkerPanel.setLayout(new java.awt.GridLayout(2, 0));

        jLabel17.setText("probability");
        randomWalkerPanel.add(jLabel17);

        pTextField1.setText("0.01");
        pTextField1.setToolTipText("");
        pTextField1.setPreferredSize(new java.awt.Dimension(40, 20));
        pTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTextField1ActionPerformed(evt);
            }
        });
        randomWalkerPanel.add(pTextField1);

        jLabel1.setText(" ");
        randomWalkerPanel.add(jLabel1);

        runRandomWalker.setText("Run Random Walker");
        runRandomWalker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runRandomWalkerActionPerformed(evt);
            }
        });
        randomWalkerPanel.add(runRandomWalker);

        getContentPane().add(randomWalkerPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void runRandomWalkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runRandomWalkerActionPerformed
        if(frame.idAndTimeNodeSelectedEpidemiology == null)
            JOptionPane.showMessageDialog(this,"Please select a node in a specific timestamp first.");
        else
        {
            String[] nodeSelected = frame.idAndTimeNodeSelectedEpidemiology.split(" ");
            frame.netLayoutInlineNew.randomWalker(nodeSelected[0], Integer.parseInt(nodeSelected[1]),Double.parseDouble(pTextField1.getText()));
        }
    }//GEN-LAST:event_runRandomWalkerActionPerformed

    private void pTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTextField1ActionPerformed

    
    public void display() {
        this.pack();
        this.setLocation(frame.getWidth()/2 + this.getWidth()/2, frame.getHeight()/2 - this.getHeight()/2);
        this.setVisible(true);
    }
    
    private MainForm frame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JTextField pTextField1;
    private javax.swing.JPanel randomWalkerPanel;
    private javax.swing.JButton runRandomWalker;
    // End of variables declaration//GEN-END:variables

}