/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2014-2019 Bruno Augusto Nassif Travencolo.
 * All Rights Reserved.
 *
 * This file is part of DyNetVis Project (DyNetVis).
 *
 * How to cite this software:
 *  
@inproceedings{Linhares:2017:DSV:3019612.3019686,
 author = {Linhares, Claudio D. G. and Traven\c{c}olo, Bruno A. N. and Paiva, Jose Gustavo S. and Rocha, Luis E. C.},
 title = {DyNetVis: A System for Visualization of Dynamic Networks},
 booktitle = {Proceedings of the Symposium on Applied Computing},
 series = {SAC '17},
 year = {2017},
 isbn = {978-1-4503-4486-9},
 location = {Marrakech, Morocco},
 pages = {187--194},
 numpages = {8},
 url = {http://doi.acm.org/10.1145/3019612.3019686},
 doi = {10.1145/3019612.3019686},
 acmid = {3019686},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {complex networks, dynamic graph visualization, dynamic networks, recurrent neighbors, temporal activity map},
} 
 *  
 * DyNetVis is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * DyNetVis is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Lab of Complex Network Visualization at 
 * Federal University of Uberlândia, Brazil - (https://sites.google.com/view/dynetvis/team?authuser=0). 
 * The initial developer of the original code is Claudio D. G. Linhares <claudiodgl@gmail.com>.
 *
 * Contributor(s): Jean R. Ponciano -- jeanrobertop@gmail.com, Luis E. C. Rocha -- luis.rocha@ugent.be, 
 * José Gustavo S. Paiva -- gustavo@ufu.br, Bruno A. N. Travençolo -- travencolo@gmail.com
 *
 * You should have received a copy of the GNU General Public License along 
 * with DyNetVis. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */
package forms;

import java.util.ArrayList;
import javax.swing.JDialog;

/**
 *
 * @author Jean
 */
public class SeVisSettings extends JDialog {

    /**
     * Creates new form SeVisSettings
     */
    public SeVisSettings() {
        initComponents();
    }
    
    private MainForm frame;
    public SeVisSettings(MainForm f) {
        initComponents();
        setAlwaysOnTop(true);
        frame = f;
           
        
        
    }
    
    private static SeVisSettings instance;
    public static SeVisSettings getInstance(MainForm t) {
        if (instance == null || instance.getParent() != t) {
            instance = new SeVisSettings(t);
            
        }
        return instance;
    }
    
     public void display() {
        this.pack();
        this.setLocation(frame.getWidth()/2 + this.getWidth()/2, frame.getHeight()/2 - this.getHeight()/2);
        this.setVisible(true);
        
                this.wsizeSliderSevis.setMinimum(1);
        this.wsizeSliderSevis.setMaximum(500);
        this.wsizeSliderSevis.setValue(100);
        
        this.kSpaceSavingSevisSlider.setMinimum(1);
        int nroNosRede = Integer.parseInt(frame.numberNodes);
        this.kSpaceSavingSevisSlider.setMaximum(nroNosRede);
        this.kSpaceSavingSevisSlider.setValue((int)(0.25*nroNosRede));
        
        this.trSevisSlider.setMinimum(1);
        this.trSevisSlider.setMaximum(1000);
        this.trSevisSlider.setValue(800);
        
        this.trSevisTextBox.setEditable(false);
        this.kSpaceSavingSevisTextBox.setEditable(false);
        this.windowSizeTextboxSevis.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourcePanelSevis = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        comDetectionSevisComboBox = new javax.swing.JComboBox<>();
        jLabelWsizeSevis = new javax.swing.JLabel();
        windowSizeTextboxSevis = new javax.swing.JTextField();
        wsizeSliderSevis = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        kSpaceSavingSevisSlider = new javax.swing.JSlider();
        kSpaceSavingSevisTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        trSevisTextBox = new javax.swing.JTextField();
        trSevisSlider = new javax.swing.JSlider();
        formSevisHeaderLabel = new javax.swing.JLabel();
        SevisSettingsOK = new javax.swing.JButton();
        SevisSettingsCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maintained = new javax.swing.JTextField();
        discarded = new javax.swing.JTextField();
        ks = new javax.swing.JTextField();
        pvalue = new javax.swing.JTextField();

        sourcePanelSevis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sourcePanelSevis.setPreferredSize(new java.awt.Dimension(450, 120));

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel60.setText("Commun. Detection Algorithm:                             ");
        jLabel60.setToolTipText("");
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        comDetectionSevisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Louvain" }));
        comDetectionSevisComboBox.setMinimumSize(new java.awt.Dimension(124, 20));
        comDetectionSevisComboBox.setPreferredSize(new java.awt.Dimension(124, 20));

        jLabelWsizeSevis.setText("Window size:");
        jLabelWsizeSevis.setPreferredSize(new java.awt.Dimension(100, 16));

        windowSizeTextboxSevis.setPreferredSize(new java.awt.Dimension(100, 22));

        wsizeSliderSevis.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wsizeSliderSevisStateChanged(evt);
            }
        });

        jLabel1.setText("k (Space-Saving):");
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));

        kSpaceSavingSevisSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kSpaceSavingSevisSliderStateChanged(evt);
            }
        });

        kSpaceSavingSevisTextBox.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel2.setText("Tr:");

        trSevisTextBox.setPreferredSize(new java.awt.Dimension(100, 22));

        trSevisSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trSevisSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout sourcePanelSevisLayout = new javax.swing.GroupLayout(sourcePanelSevis);
        sourcePanelSevis.setLayout(sourcePanelSevisLayout);
        sourcePanelSevisLayout.setHorizontalGroup(
            sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourcePanelSevisLayout.createSequentialGroup()
                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sourcePanelSevisLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel60)
                        .addGap(5, 5, 5)
                        .addComponent(comDetectionSevisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trSevisTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trSevisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createSequentialGroup()
                                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelWsizeSevis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createSequentialGroup()
                                        .addComponent(windowSizeTextboxSevis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(wsizeSliderSevis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createSequentialGroup()
                                        .addComponent(kSpaceSavingSevisTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(kSpaceSavingSevisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        sourcePanelSevisLayout.setVerticalGroup(
            sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourcePanelSevisLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sourcePanelSevisLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel60))
                    .addComponent(comDetectionSevisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowSizeTextboxSevis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelWsizeSevis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wsizeSliderSevis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kSpaceSavingSevisTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kSpaceSavingSevisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sourcePanelSevisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trSevisTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(trSevisSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        formSevisHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formSevisHeaderLabel.setText("SEVis Settings");
        formSevisHeaderLabel.setToolTipText("");
        formSevisHeaderLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        formSevisHeaderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SevisSettingsOK.setText("OK");
        SevisSettingsOK.setMaximumSize(new java.awt.Dimension(65, 23));
        SevisSettingsOK.setMinimumSize(new java.awt.Dimension(65, 23));
        SevisSettingsOK.setPreferredSize(new java.awt.Dimension(65, 23));
        SevisSettingsOK.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SevisSettingsOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevisSettingsOKActionPerformed(evt);
            }
        });

        SevisSettingsCancelar.setText("Cancel");
        SevisSettingsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevisSettingsCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText(" KS-distance: ");

        jLabel4.setText(" p-value:");

        jLabel5.setText(" # Maintened edges: ");

        jLabel6.setText(" # Discarded edges:");

        maintained.setEditable(false);
        maintained.setPreferredSize(new java.awt.Dimension(100, 22));
        maintained.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainedActionPerformed(evt);
            }
        });

        discarded.setEditable(false);

        ks.setEditable(false);

        pvalue.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(discarded))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maintained, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ks)
                    .addComponent(pvalue))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(maintained, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(discarded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sourcePanelSevis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(formSevisHeaderLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(SevisSettingsOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SevisSettingsCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formSevisHeaderLabel)
                .addGap(31, 31, 31)
                .addComponent(sourcePanelSevis, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SevisSettingsOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SevisSettingsCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wsizeSliderSevisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wsizeSliderSevisStateChanged

        windowSizeTextboxSevis.setText(wsizeSliderSevis.getValue()+"");
    }//GEN-LAST:event_wsizeSliderSevisStateChanged

    private void kSpaceSavingSevisSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kSpaceSavingSevisSliderStateChanged
                kSpaceSavingSevisTextBox.setText(kSpaceSavingSevisSlider.getValue()+"");

    }//GEN-LAST:event_kSpaceSavingSevisSliderStateChanged

    private void trSevisSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trSevisSliderStateChanged
        trSevisTextBox.setText(trSevisSlider.getValue()/1000.0 +"");
    }//GEN-LAST:event_trSevisSliderStateChanged

    private void SevisSettingsOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevisSettingsOKActionPerformed
        frame.getNetInline().windowSizeValue = wsizeSliderSevis.getValue();
        frame.getNetInline().kNodes = kSpaceSavingSevisSlider.getValue();
        frame.getNetInline().margemAceitavelParaDiferencaProporcaoArestasIntra =  1.0 - Double.parseDouble(trSevisTextBox.getText());
        frame.getNetInline().SEVisCommunityDetcMethod = comDetectionSevisComboBox.getSelectedItem().toString();
        
        frame.getNetInline().isResolucaoDinamica = false;
        ArrayList retornoEdgeSampling = frame.getNetInline().edgeSampling("SEVis", frame.numberNodes, false);
        
        util.KSTest resultado = (util.KSTest) retornoEdgeSampling.get(0);
        ks.setText(String.format("%.4f",resultado.d));
        pvalue.setText(String.format("%.4f",resultado.pvalue));
        discarded.setText(retornoEdgeSampling.get(1).toString());
        maintained.setText(retornoEdgeSampling.get(2).toString());
        
        SevisSettingsOK.setEnabled(false);
        SevisSettingsCancelar.setText("Close");
        

    }//GEN-LAST:event_SevisSettingsOKActionPerformed

    private void SevisSettingsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevisSettingsCancelarActionPerformed
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SevisSettingsCancelarActionPerformed

    private void maintainedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton SevisSettingsCancelar;
    public javax.swing.JButton SevisSettingsOK;
    private javax.swing.JComboBox<String> comDetectionSevisComboBox;
    private javax.swing.JTextField discarded;
    private javax.swing.JLabel formSevisHeaderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabelWsizeSevis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider kSpaceSavingSevisSlider;
    private javax.swing.JTextField kSpaceSavingSevisTextBox;
    private javax.swing.JTextField ks;
    private javax.swing.JTextField maintained;
    private javax.swing.JTextField pvalue;
    public javax.swing.JPanel sourcePanelSevis;
    private javax.swing.JSlider trSevisSlider;
    private javax.swing.JTextField trSevisTextBox;
    private javax.swing.JTextField windowSizeTextboxSevis;
    private javax.swing.JSlider wsizeSliderSevis;
    // End of variables declaration//GEN-END:variables
}
